Repository vincentdchan/quill-next, pull requests merged in 2025-05, with the labels that each got.

#14 chore: Update quill-next and quill-next-react versions to 2.0.4-alpha
  packages/website/src/components/Sandpack.jsx
Labels: change:documentation

#15 Feat: doc 2
  packages/quill-next-react/package.json
  packages/quill-next-react/src/hooks/use-next-link-blot.ts
  packages/quill-next-react/src/messages.ts
  packages/quill-next-react/src/notion-like/plugins/notion-link-toolbar.plugin.tsx
  packages/quill-next-react/src/plugins/link-toolbar-plugin.tsx
  packages/website/content/docs/configuration.mdx
  packages/website/content/docs/installation.mdx
  packages/website/content/docs/react/editor.mdx
Labels: change:documentation

#16 Feat/doc plugins
  packages/quill-next-react/src/index.ts
  packages/quill-next-react/src/notion-like/plugins/notion-toolbar-plugin.tsx
  packages/website/content/docs/configuration.mdx
  packages/website/content/docs/formats.mdx
  packages/website/content/docs/hooks.mdx
  packages/website/content/docs/installation.mdx
  packages/website/content/docs/modules/legacy-toolbar.mdx
  packages/website/content/docs/plugins/builtin-plugins.mdx
  packages/website/content/docs/plugins/plugins.mdx
  packages/website/content/docs/quickstart.mdx
  packages/website/content/docs/react/use-react-blot.mdx
  packages/website/content/docs/why-quill-next.mdx
  packages/website/src/components/Editor.jsx
  packages/website/src/components/Layout.jsx
  packages/website/src/components/PostLayout.jsx
  packages/website/src/components/Sandpack.jsx
  packages/website/src/data/docs.tsx
  packages/website/src/pages/styles.scss
Labels: change:documentation

#17 Feat/notion like enhanced
  packages/quill-next-react/package.json
  packages/quill-next-react/src/Global.ts
  packages/quill-next-react/src/classes/toolbar-signal.class.ts
  packages/quill-next-react/src/components/rect-anchor.component.tsx
  packages/quill-next-react/src/enhanced-editor.stories.tsx
  packages/quill-next-react/src/hooks/use-toolbar-signal.ts
  packages/quill-next-react/src/index.ts
  packages/quill-next-react/src/notion-like/components/notion-like-link-input.component.style.ts
  packages/quill-next-react/src/notion-like/components/notion-like-link-input.component.tsx
  packages/quill-next-react/src/notion-like/components/notion-like-quill-editor.component.tsx
  packages/quill-next-react/src/notion-like/components/notion-link-toolbar.component.style.ts
  packages/quill-next-react/src/notion-like/components/notion-toolbar.component.tsx
  packages/quill-next-react/src/notion-like/components/toolbar/bold.svg
  packages/quill-next-react/src/notion-like/components/toolbar/chevron-down.svg
  packages/quill-next-react/src/notion-like/components/toolbar/italic.svg
  packages/quill-next-react/src/notion-like/components/toolbar/link.svg
  packages/quill-next-react/src/notion-like/components/toolbar/notion-toolbar-button.component.style.ts
  packages/quill-next-react/src/notion-like/components/toolbar/notion-toolbar-button.component.tsx
  packages/quill-next-react/src/notion-like/components/toolbar/notion-toolbar.component.style.ts
  packages/quill-next-react/src/notion-like/components/toolbar/notion-toolbar.component.tsx
  packages/quill-next-react/src/notion-like/components/toolbar/strike.svg
  packages/quill-next-react/src/notion-like/components/toolbar/underline.svg
  packages/quill-next-react/src/notion-like/index.ts
  packages/quill-next-react/src/notion-like/plugins/notion-toolbar-plugin.tsx
  packages/quill-next-react/src/plugins/command-plugin.tsx
  packages/quill-next-react/src/plugins/link-toolbar-plugin.tsx
  packages/quill-next-react/src/plugins/toolbar-plugin.tsx
  packages/quill-next-react/src/utils/bounds.ts
  packages/quill-next-react/src/utils/url.spec.ts
  packages/quill-next-react/src/utils/url.ts
  packages/quill-next-react/vite.config.ts
  packages/website/src/pages/base.css
  pnpm-lock.yaml
Labels: change:feature

#18 chore: Update quill-delta dependency to quill-delta-es and bump versi…
  packages/quill-next-react/package.json
  packages/quill/package.json
  packages/quill/src/blots/block.ts
  packages/quill/src/blots/scroll.ts
  packages/quill/src/core.ts
  packages/quill/src/core/editor.ts
  packages/quill/src/core/quill.ts
  packages/quill/src/modules/clipboard.ts
  packages/quill/src/modules/history.ts
  packages/quill/src/modules/input.ts
  packages/quill/src/modules/keyboard.ts
  packages/quill/src/modules/syntax.ts
  packages/quill/src/modules/table.ts
  packages/quill/src/modules/tableEmbed.ts
  packages/quill/src/modules/toolbar.ts
  packages/quill/src/modules/uploader.ts
  packages/quill/test/fuzz/editor.spec.ts
  packages/quill/test/fuzz/tableEmbed.spec.ts
  packages/quill/test/unit/blots/scroll.spec.ts
  packages/quill/test/unit/core/editor.spec.ts
  packages/quill/test/unit/core/quill.spec.ts
  packages/quill/test/unit/formats/align.spec.ts
  packages/quill/test/unit/formats/code.spec.ts
  packages/quill/test/unit/formats/color.spec.ts
  packages/quill/test/unit/formats/header.spec.ts
  packages/quill/test/unit/formats/indent.spec.ts
  packages/quill/test/unit/formats/link.spec.ts
  packages/quill/test/unit/formats/list.spec.ts
  packages/quill/test/unit/formats/table.spec.ts
  packages/quill/test/unit/modules/clipboard.spec.ts
  packages/quill/test/unit/modules/history.spec.ts
  packages/quill/test/unit/modules/syntax.spec.ts
  packages/quill/test/unit/modules/table.spec.ts
  packages/quill/test/unit/modules/tableEmbed.spec.ts
  pnpm-lock.yaml
Labels: change:refactor

#19 Feat/homepage 2
  README.md
  packages/quill-next-react/package.json
  packages/quill-next-react/src/enhanced-editor.stories.tsx
  packages/quill-next-react/src/index.ts
  packages/quill-next-react/src/notion-like/index.ts
  packages/quill/package.json
  packages/website/content/docs/configuration.mdx
  packages/website/content/docs/hooks.mdx
  packages/website/content/docs/installation.mdx
  packages/website/content/docs/plugins/builtin-plugins.mdx
  packages/website/content/docs/plugins/plugins.mdx
  packages/website/content/docs/quickstart.mdx
  packages/website/content/docs/react/editor.mdx
  packages/website/content/docs/react/use-react-blot.mdx
  packages/website/content/docs/why-quill-next.mdx
  packages/website/src/components/DeltaPreview.tsx
  packages/website/src/components/Editor.jsx
  packages/website/src/components/EnhancedEditor.tsx
  packages/website/src/pages/index.jsx
  pnpm-lock.yaml
Labels: change:refactor

#20 Feat/homepage 3
  packages/quill-next-react/package.json
  packages/quill-next-react/src/notion-like/components/notion-like-link-input.component.tsx
  packages/website/public/assets/images/channels/channel0.png
  packages/website/public/assets/images/channels/channel1.png
  packages/website/src/components/AnimatedBackground.tsx
  packages/website/src/components/DeltaPreview.module.scss
  packages/website/src/components/DeltaPreview.tsx
  packages/website/src/components/MDX.jsx
  packages/website/src/components/ShadertoyReact.tsx
  packages/website/src/pages/index.jsx
  packages/website/src/pages/styles.scss
Labels: change:documentation

#21 Feat/homepage 4
  packages/website/env.js
  packages/website/package.json
  packages/website/src/components/SEO.jsx
  packages/website/src/pages/index.jsx
Labels: change:documentation

#23 Feat/line type
  packages/quill-next-react/package.json
  packages/quill-next-react/src/components/dropdown-mask.component.style.ts
  packages/quill-next-react/src/components/dropdown-mask.component.tsx
  packages/quill-next-react/src/notion-like/components/notion-like-link-input.component.style.ts
  packages/quill-next-react/src/notion-like/components/notion-like-link-input.component.tsx
  packages/quill-next-react/src/notion-like/components/notion-like-quill-editor.component.stories.ts
  packages/quill-next-react/src/notion-like/components/toolbar/checkmark.svg
  packages/quill-next-react/src/notion-like/components/toolbar/notion-like-dropdown-menu.style.ts
  packages/quill-next-react/src/notion-like/components/toolbar/notion-like-dropdown-menu.tsx
  packages/quill-next-react/src/notion-like/components/toolbar/notion-like-select.component.style.ts
  packages/quill-next-react/src/notion-like/components/toolbar/notion-like-select.component.tsx
  packages/quill-next-react/src/notion-like/components/toolbar/notion-toolbar-button.component.tsx
  packages/quill-next-react/src/notion-like/components/toolbar/notion-toolbar.component.tsx
Labels: change:feature

#24 chore/return type of component
  packages/quill-next-react/.eslintrc.cjs
  packages/quill-next-react/package.json
  packages/quill-next-react/src/classes/toolbar-signal.class.ts
  packages/quill-next-react/src/components/dropdown-mask.component.tsx
  packages/quill-next-react/src/components/quill-next-image.component.tsx
  packages/quill-next-react/src/components/rect-anchor.component.tsx
  packages/quill-next-react/src/editor.component.stories.tsx
  packages/quill-next-react/src/editor.component.tsx
  packages/quill-next-react/src/enhanced-editor.stories.tsx
  packages/quill-next-react/src/forked-registry.spec.ts
  packages/quill-next-react/src/hooks/use-dispose.ts
  packages/quill-next-react/src/hooks/use-next-link-blot.ts
  packages/quill-next-react/src/hooks/use-quill-arrow-index.ts
  packages/quill-next-react/src/hooks/use-quill-editor-change.ts
  packages/quill-next-react/src/hooks/use-quill-event.ts
  packages/quill-next-react/src/hooks/use-quill-selection-change.ts
  packages/quill-next-react/src/hooks/use-quill-text-change.ts
  packages/quill-next-react/src/hooks/use-react-blot.ts
  packages/quill-next-react/src/hooks/use-toolbar-signal.ts
  packages/quill-next-react/src/notion-like/components/notion-like-link-input.component.tsx
  packages/quill-next-react/src/notion-like/components/notion-like-quill-editor.component.tsx
  packages/quill-next-react/src/notion-like/components/notion-link-toolbar.component.tsx
  packages/quill-next-react/src/notion-like/components/notion-menu-list.component.tsx
  packages/quill-next-react/src/notion-like/components/toolbar/notion-like-dropdown-menu.tsx
  packages/quill-next-react/src/notion-like/components/toolbar/notion-like-select.component.tsx
  packages/quill-next-react/src/notion-like/components/toolbar/notion-toolbar-button.component.tsx
  packages/quill-next-react/src/notion-like/components/toolbar/notion-toolbar.component.tsx
  packages/quill-next-react/src/notion-like/plugins/notion-link-toolbar.plugin.tsx
  packages/quill-next-react/src/notion-like/plugins/notion-toolbar-plugin.tsx
  packages/quill-next-react/src/plugins/command-plugin.tsx
  packages/quill-next-react/src/plugins/link-toolbar-plugin.tsx
  packages/quill-next-react/src/plugins/slash-command-plugin.tsx
  packages/quill-next-react/src/plugins/toolbar-plugin.tsx
  packages/website/src/components/AnimatedBackground.tsx
Labels: change:refactor

#25 refactor: Enhance ToolbarPlugin with scroll handling and cleanup
  packages/quill-next-react/package.json
  packages/quill-next-react/src/plugins/toolbar-plugin.tsx
Labels: change:bugfix

#26 Feat/homepage 5
  packages/website/content/docs/plugins/builtin-plugins.mdx
  packages/website/src/components/Sandpack.jsx
  packages/website/src/pages/base.css
  packages/website/src/pages/index.jsx
  packages/website/src/pages/styles.scss
Labels: change:documentation

#27 Feat/enhanced image
  packages/quill-next-react/package.json
  packages/quill-next-react/src/components/image-resize-tool.style.ts
  packages/quill-next-react/src/components/image-resize-tool.tsx
  packages/quill-next-react/src/components/quill-next-image.component.tsx
  packages/quill-next-react/src/components/quill-next-image.stories.tsx
  packages/quill-next-react/src/components/quill-next-image.style.ts
  packages/quill-next-react/src/components/quill-next-image.tsx
  packages/quill-next-react/src/hooks/use-block-embed-blot.tsx
  packages/quill-next-react/src/hooks/use-embed-blot.ts
  packages/quill-next-react/src/index.ts
  packages/quill-next-react/src/notion-like/components/notion-like-quill-editor.component.stories.ts
  packages/quill-next-react/src/notion-like/components/notion-like-quill-editor.component.tsx
  packages/quill/package.json
  packages/quill/src/quill.ts
  pnpm-lock.yaml
Labels: change:feature

#28 Feat/code format
  packages/quill-next-react/src/notion-like/components/notion-like-tooltip.style.ts
  packages/quill-next-react/src/notion-like/components/notion-like-tooltip.tsx
  packages/quill-next-react/src/notion-like/components/toolbar/code.svg
  packages/quill-next-react/src/notion-like/components/toolbar/notion-like-select.style.ts
  packages/quill-next-react/src/notion-like/components/toolbar/notion-like-select.tsx
  packages/quill-next-react/src/notion-like/components/toolbar/notion-toolbar-button.component.tsx
  packages/quill-next-react/src/notion-like/components/toolbar/notion-toolbar-button.style.ts
  packages/quill-next-react/src/notion-like/components/toolbar/notion-toolbar-button.tsx
  packages/quill-next-react/src/notion-like/components/toolbar/notion-toolbar.style.ts
  packages/quill-next-react/src/notion-like/components/toolbar/notion-toolbar.tsx
  packages/quill-next-react/src/notion-like/hooks/use-tooltip-utils.ts
  packages/quill-next-react/src/notion-like/index.ts
  packages/quill-next-react/src/notion-like/plugins/notion-toolbar-plugin.tsx
  packages/website/src/components/Sandpack.jsx
Labels: change:feature

#32 Soft breaks
  packages/quill/src/blots/block.ts
  packages/quill/src/blots/break.ts
  packages/quill/src/blots/soft-break.ts
  packages/quill/src/core.ts
  packages/quill/src/core/editor.ts
  packages/quill/src/modules/clipboard.ts
  packages/quill/src/modules/keyboard.ts
  packages/quill/test/e2e/__dev_server__/index.html
  packages/quill/test/unit/__helpers__/factory.ts
  packages/quill/test/unit/core/editor.spec.ts
  packages/quill/test/unit/modules/clipboard.spec.ts
Labels: change:feature
